# Generated by Django 5.1.6 on 2025-02-18 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="views",
            field=models.ManyToManyField(
                blank=True, related_name="views", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
